# Generated by Django 3.2.7 on 2021-09-10 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('capital_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=15)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_purchaseorder_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_purchaseorder_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trx_purchase_order',
            },
        ),
    ]
